export const KEYS = {
  lifetimePops: 'lifetimePops',
  sessionStart: 'sessionStart',
  bestStreak: 'bestStreak',
  currentStreak: 'currentStreak',
  lastStreakDate: 'lastStreakDate',
  theme: 'theme',
  credits: 'credits',
  companyIndex: 'companyIndex',
  popsThisContract: 'popsThisContract',
  contractComplete: 'contractComplete',
  prestigeCount: 'prestigeCount',
  companiesCompleted: 'companiesCompleted',
  sheetResetVersion: 'sheetResetVersion',
  ownedUpgradesJson: 'ownedUpgradesJson',
  hasSeenPrestigeExplainer: 'hasSeenPrestigeExplainer',
  hapticsEnabled: 'hapticsEnabled',
  soundEnabled: 'soundEnabled',
  flair: 'flair',
  lifetimeContractsCompleted: 'lifetimeContractsCompleted',
  phase3EconomyMigrated: 'phase3EconomyMigrated',
  ownedCosmeticsJson: 'ownedCosmeticsJson',
  claimedAchievementsJson: 'claimedAchievementsJson',
  pendingOffersJson: 'pendingOffersJson',
  selectedOfferIndex: 'selectedOfferIndex',
  activeModifierIdsJson: 'activeModifierIdsJson',
  visitedProgressTab: 'visitedProgressTab',
  visitedShopTab: 'visitedShopTab',
  bubbleTintHex: 'bubbleTintHex',
} as const;

export const ALL_KEYS: string[] = [...Object.values(KEYS)];
